server:
	java -Djava.security.policy=a.policy -Djava.rmi.server.codebase=file:///Users/tasukutakahashi/itask/java/rpc/rmi2/ HelloImpl localhost

client:
	java -Djava.security.policy=fire.policy Client localhost
