test:
	java -Djava.security.policy=java.policy -Djava.rmi.server.codebase=file:///Users/tasukutakahashi/iTask/java/rpc/kantan KantanHelloImpl

client:
	java -Djava.security.policy=java.policy Client 

