// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class LaasServer_Stub
    extends java.rmi.server.RemoteStub
    implements LaasServerInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getTotalPassingYardage_0;
    private static java.lang.reflect.Method $method_getTotalRunningYardage_1;
    private static java.lang.reflect.Method $method_getTotalTurnovers_2;
    
    static {
	try {
	    $method_getTotalPassingYardage_0 = LaasServerInterface.class.getMethod("getTotalPassingYardage", new java.lang.Class[] {java.lang.String.class});
	    $method_getTotalRunningYardage_1 = LaasServerInterface.class.getMethod("getTotalRunningYardage", new java.lang.Class[] {java.lang.String.class});
	    $method_getTotalTurnovers_2 = LaasServerInterface.class.getMethod("getTotalTurnovers", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public LaasServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getTotalPassingYardage(String)
    public int getTotalPassingYardage(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTotalPassingYardage_0, new java.lang.Object[] {$param_String_1}, -6560239731255704818L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTotalRunningYardage(String)
    public int getTotalRunningYardage(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTotalRunningYardage_1, new java.lang.Object[] {$param_String_1}, 6758634289860336870L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getTotalTurnovers(String)
    public int getTotalTurnovers(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getTotalTurnovers_2, new java.lang.Object[] {$param_String_1}, -4971531153650717327L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
