// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class LaasHashMapImpl_Stub
    extends java.rmi.server.RemoteStub
    implements LaasHashMap, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_clear_0;
    private static java.lang.reflect.Method $method_containsKey_1;
    private static java.lang.reflect.Method $method_containsValue_2;
    private static java.lang.reflect.Method $method_entrySet_3;
    private static java.lang.reflect.Method $method_get_4;
    private static java.lang.reflect.Method $method_isEmpty_5;
    private static java.lang.reflect.Method $method_keySet_6;
    private static java.lang.reflect.Method $method_put_7;
    private static java.lang.reflect.Method $method_putAll_8;
    private static java.lang.reflect.Method $method_remove_9;
    private static java.lang.reflect.Method $method_size_10;
    private static java.lang.reflect.Method $method_values_11;
    
    static {
	try {
	    $method_clear_0 = LaasHashMap.class.getMethod("clear", new java.lang.Class[] {});
	    $method_containsKey_1 = LaasHashMap.class.getMethod("containsKey", new java.lang.Class[] {java.lang.Object.class});
	    $method_containsValue_2 = LaasHashMap.class.getMethod("containsValue", new java.lang.Class[] {java.lang.Object.class});
	    $method_entrySet_3 = LaasHashMap.class.getMethod("entrySet", new java.lang.Class[] {});
	    $method_get_4 = LaasHashMap.class.getMethod("get", new java.lang.Class[] {java.lang.Object.class});
	    $method_isEmpty_5 = LaasHashMap.class.getMethod("isEmpty", new java.lang.Class[] {});
	    $method_keySet_6 = LaasHashMap.class.getMethod("keySet", new java.lang.Class[] {});
	    $method_put_7 = LaasHashMap.class.getMethod("put", new java.lang.Class[] {java.lang.Object.class, java.lang.Object.class});
	    $method_putAll_8 = LaasHashMap.class.getMethod("putAll", new java.lang.Class[] {java.util.Map.class});
	    $method_remove_9 = LaasHashMap.class.getMethod("remove", new java.lang.Class[] {java.lang.Object.class});
	    $method_size_10 = LaasHashMap.class.getMethod("size", new java.lang.Class[] {});
	    $method_values_11 = LaasHashMap.class.getMethod("values", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public LaasHashMapImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of clear()
    public void clear()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_clear_0, null, -7475254351993695499L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of containsKey(Object)
    public boolean containsKey(java.lang.Object $param_Object_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_containsKey_1, new java.lang.Object[] {$param_Object_1}, -3172792759261346218L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of containsValue(Object)
    public void containsValue(java.lang.Object $param_Object_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_containsValue_2, new java.lang.Object[] {$param_Object_1}, 1509746859406952294L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of entrySet()
    public java.util.Set entrySet()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_entrySet_3, null, -7629022308093071445L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of get(Object)
    public java.lang.Object get(java.lang.Object $param_Object_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_get_4, new java.lang.Object[] {$param_Object_1}, 6832719500409870279L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of isEmpty()
    public boolean isEmpty()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_isEmpty_5, null, 9136275027625107786L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of keySet()
    public java.util.Set keySet()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_keySet_6, null, -3654007840389775963L);
	    return ((java.util.Set) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of put(Object, Object)
    public java.lang.Object put(java.lang.Object $param_Object_1, java.lang.Object $param_Object_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_put_7, new java.lang.Object[] {$param_Object_1, $param_Object_2}, 343023290247182271L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of putAll(Map)
    public void putAll(java.util.Map $param_Map_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_putAll_8, new java.lang.Object[] {$param_Map_1}, 6292447698899276240L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of remove(Object)
    public java.lang.Object remove(java.lang.Object $param_Object_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_remove_9, new java.lang.Object[] {$param_Object_1}, 7236030930369834760L);
	    return ((java.lang.Object) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of size()
    public int size()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_size_10, null, 4495240443643581991L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of values()
    public java.util.Collection values()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_values_11, null, -2518452077531405751L);
	    return ((java.util.Collection) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
